// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sampleGamma
Rcpp::List sampleGamma(arma::umat Gammas, bool gamma_sampler_bandit, double a_pi, double b_pi);
RcppExport SEXP _GPTCM_sampleGamma(SEXP GammasSEXP, SEXP gamma_sampler_banditSEXP, SEXP a_piSEXP, SEXP b_piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type Gammas(GammasSEXP);
    Rcpp::traits::input_parameter< bool >::type gamma_sampler_bandit(gamma_sampler_banditSEXP);
    Rcpp::traits::input_parameter< double >::type a_pi(a_piSEXP);
    Rcpp::traits::input_parameter< double >::type b_pi(b_piSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleGamma(Gammas, gamma_sampler_bandit, a_pi, b_pi));
    return rcpp_result_gen;
END_RCPP
}
