# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multivariate ARMS via Gibbs sampler
#'
#' @param n Number of samples to draw
#' @param every How many samples to draw for generating each sample; only the last 'n' draws will be kept; but it seems not work for every>1, not know why
#' @param ninit Number of initials as meshgrid values for envelop search
#' @param convex Adjustment for convexity (non-negative value, default 1.0)
#' @param npoint Maximum number of envelope points
#'
arms_gibbs_xi <- function(n, every, ninit, minRange, maxRange, metropolis, simple, convex, npoint, currentPars, vA, vB, datX0, datProportion, datEvent, weibullS) {
    .Call('_GPTCM_arms_gibbs_xi', PACKAGE = 'GPTCM', n, every, ninit, minRange, maxRange, metropolis, simple, convex, npoint, currentPars, vA, vB, datX0, datProportion, datEvent, weibullS)
}

#' Rcpp wrapper for ARS algorithm
#'
#' @param n number of variates to draw
#' @param log_dens log density function, a function with a single parameter
#' @param initialPoints at least 2 points in support to seed algorithm
#' @param minRange lower bound of support
#' @param maxRange upper bound of support
#'
ars <- function(n, initialPoints, minRange, maxRange, jj, xis, vA, vB, datX0, datProportion, datEvent, weibullS) {
    .Call('_GPTCM_ars', PACKAGE = 'GPTCM', n, initialPoints, minRange, maxRange, jj, xis, vA, vB, datX0, datProportion, datEvent, weibullS)
}

#' Duplicate wrapper for ARS algorithm for debugging. This version
#' returns the algorithm state as well as the variates.
#'
#' @param n number of variates to draw
#' @param log_dens log density function, a function with a single parameter
#' @param initialPoints at least 2 points in support to seed algorithm
#' @param minRange lower bound of support
#' @param maxRange upper bound of support
#' @param maxiter maximum number of iterations; zero if no limit
#'
ars_debug <- function(n, initialPoints, minRange, maxRange, maxiter, jj, xis, vA, vB, datX0, datProportion, datEvent, weibullS) {
    .Call('_GPTCM_ars_debug', PACKAGE = 'GPTCM', n, initialPoints, minRange, maxRange, maxiter, jj, xis, vA, vB, datX0, datProportion, datEvent, weibullS)
}

#' Gibbs sampling for multivariate ARS
#'
#' @param n number of variates to draw
#' @param initialPoints this can be a matrix in multivariate case
#'
ars_gibbs <- function(n, initialPoints, minRange, maxRange, par, vA, vB, datX0, datProportion, datEvent, weibullS) {
    .Call('_GPTCM_ars_gibbs', PACKAGE = 'GPTCM', n, initialPoints, minRange, maxRange, par, vA, vB, datX0, datProportion, datEvent, weibullS)
}

sampleGamma <- function(Gammas, gamma_sampler_bandit, a_pi, b_pi) {
    .Call('_GPTCM_sampleGamma', PACKAGE = 'GPTCM', Gammas, gamma_sampler_bandit, a_pi, b_pi)
}

