# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp wrapper for adsamp algorithm
#'
#' @param n number of variates to draw
#' @param log_dens log density function, a function with a single parameter
#' @param initialPoints at least 2 points in support to seed algorithm
#' @param minRange lower bound of support
#' @param maxRange upper bound of support
#'
ars <- function(n, initialPoints, minRange, maxRange, jj, xis, vA, vB, datX0, datProportion, datEvent, weibullS) {
    .Call('_GPTCM_ars', PACKAGE = 'GPTCM', n, initialPoints, minRange, maxRange, jj, xis, vA, vB, datX0, datProportion, datEvent, weibullS)
}

#' Duplicate wrapper for adsamp algorithm for debugging. This version
#' returns the algorithm state as well as the variates.
#'
#' @param n number of variates to draw
#' @param log_dens log density function, a function with a single parameter
#' @param initialPoints at least 2 points in support to seed algorithm
#' @param minRange lower bound of support
#' @param maxRange upper bound of support
#' @param maxiter maximum number of iterations; zero if no limit
#'
ars_debug <- function(n, initialPoints, minRange, maxRange, maxiter, jj, xis, vA, vB, datX0, datProportion, datEvent, weibullS) {
    .Call('_GPTCM_ars_debug', PACKAGE = 'GPTCM', n, initialPoints, minRange, maxRange, maxiter, jj, xis, vA, vB, datX0, datProportion, datEvent, weibullS)
}

#' Multivariate ARS via Gibbs sampler
#'
#' @param n number of variates to draw
#' @param initialPoints this can be a matrix in multivariate case
#'
arsGibbs <- function(n, initialPoints, minRange, maxRange, xis, vA, vB, datX0, datProportion, datEvent, weibullS) {
    .Call('_GPTCM_arsGibbs', PACKAGE = 'GPTCM', n, initialPoints, minRange, maxRange, xis, vA, vB, datX0, datProportion, datEvent, weibullS)
}

sampleGamma <- function(Gammas, gamma_sampler_bandit, a_pi, b_pi) {
    .Call('_GPTCM_sampleGamma', PACKAGE = 'GPTCM', Gammas, gamma_sampler_bandit, a_pi, b_pi)
}

